config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :leaderboard, only: [:index]
  resources :teams
  resources :events
  resources :team_events, except: [:index]

  root 'leaderboard#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :team_events, dependent: :destroy
  has_many :teams, through: :team_events

  validates_presence_of :name, :conducted_at

  def for_month(month = Time.current.month)
    teams = self.class.joins(teams: :team_events)
      .select("DISTINCT team_events.points, teams.name AS team_name, teams.id AS team_id, team_events.id AS team_event_id")
      .where("events.id = ?", id)
      .order('team_events.points DESC')

      teams = teams.where("date_part('month', events.conducted_at) = ? ", month) if month.present?
      teams
  end
end

app/models/leaderboard.rb
class Leaderboard
  class << self
    def current
      {
        team_status: team_status,
        event_details: event_details
      }
    end

    def team_status
      Team.joins('LEFT JOIN team_events ON teams.id = team_events.team_id')
          .select('teams.name AS team_name, COALESCE(sum(team_events.points), 0) AS total_points, teams.id')
          .group('team_name, teams.id')
          .order('total_points DESC')
    end

    def event_details
      Event.order(conducted_at: :desc)
           .select(:id, :name, :conducted_at)
    end
  end
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :team_events, dependent: :destroy
  has_many :events, through: :team_events

  validates_presence_of :name

  def for_month(month = Time.current.month)
    events = self.class.joins("INNER JOIN team_events ON team_events.team_id = teams.id INNER JOIN events on events.id = team_events.event_id")
      .select("team_events.points, date_part('month', events.conducted_at) AS event_month, events.id AS event_id")
      .select("events.name AS event_name, date_trunc('day', events.conducted_at) AS event_date, team_events.id AS team_event_id")
      .where("teams.id = ?", id)
      .order('events.conducted_at DESC')

      events = events.where("date_part('month', events.conducted_at) = ? ", month) if month.present?
      events
  end
end

app/models/team_event.rb
class TeamEvent < ApplicationRecord
  belongs_to :team
  belongs_to :event

  validates_presence_of :points
  validates :points, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def show
    # month = params[:month] || Time.current.month
    @teams = @event.for_month(nil)
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      flash[:success] = "Event #{@event.name} added successfully!"
      redirect_to action: :show, id: @event.id
    else
      flash[:error] = @event.errors.full_messages.join('<br/>')
      redirect_to action: :new
    end
  end

  def edit
  end

  def update
    @event.assign_attributes(event_params)
    if @event.save
      flash[:success] = "Event #{@event.name} updated successfully!"
    else
      flash[:error] = @event.errors.full_messages.join('<br/>')
    end
    redirect_to action: :show, id: @event.id
  end

  def index
    @events = Event.all
  end

  def destroy
    @event.destroy

    if @event.destroyed?
      flash[:success] = "Event #{@event.name} deleted successfully!"
    else
      flash[:error] = "Failed to delete the event #{@event.name}!"
    end
    redirect_to action: :index
  end

  private

  def set_event
    @event = Event.find_by(id: params[:id])
  end

  def event_params
    params.require(:event)
          .permit(:name, :conducted_at)
  end
end

app/controllers/leaderboard_controller.rb
class LeaderboardController < ApplicationController
  def index
    @leaderboard = Leaderboard.current
  end
end

app/controllers/team_events_controller.rb
class TeamEventsController < ApplicationController
  before_action :set_data
  before_action :set_team_event, only: [:edit, :update, :destroy]

  def new
    @team_event = TeamEvent.new(team: @team, event: @event)
    raise ActionController::RoutingError.new('Not Found') unless @from_event || @from_team
  end

  def create
    team_event = TeamEvent.new(team_event_params)
    if team_event.save
      flash[:success] = "Team Event added successfully!"
      redirect_page
    else
      flash[:error] = team_event.errors.full_messages.join('<br/>')
      redirect_to(action: :new, team_id: @team.try(:id), event_id: @event.try(:id), from_event: @from_event, from_team: @from_team)
    end
  end

  def update
    @team_event.assign_attributes(team_event_params)
    if @team_event.save
      flash[:success] = "Team Event updated successfully!"
      redirect_page
    else
      flash[:error] = @team_event.errors.full_messages.join('<br/>')
      redirect_to(action: :edit, team_id: @team.try(:id), event_id: @event.try(:id), from_event: @from_event, from_team: @from_team)
    end
  end

  def edit
  end

  def destroy
    @team_event.destroy

    if @team_event.destroyed?
      flash[:success] = "Team Event deleted successfully!"
    else
      flash[:error] = "Failed to delete the Team Event!"
    end
    redirect_page
  end

  private

  def set_data
    @team  = Team.find_by(id: params[:team_id] || params[:team_event].try(:[], :team_id))
    @event = Event.find_by(id: params[:event_id] || params[:team_event].try(:[], :event_id))
    @from_team = params[:from_team] && params[:from_team] == true.to_s
    @from_event = params[:from_event] && params[:from_event] == true.to_s
    @teams = Team.all
    @events = Event.all
    @assigned_teams = Team.where(id: TeamEvent.select(:team_id).where(event_id: @event.try(:id)))
    @assigned_events = Event.where(id: TeamEvent.select(:event_id).where(team_id: @team.try(:id)))
  end

  def set_team_event
    @team_event = TeamEvent.find_by(id: params[:id])
    @team = @team_event.team
    @event = @team_event.event
  end

  def team_event_params
    params.require(:team_event).permit(:points, :event_id, :team_id)
  end

  def redirect_page
    @from_team ? redirect_to(controller: :teams, action: :show, id: @team.id) : redirect_to(controller: :events, action: :show, id: @event.id)
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]
  before_action :set_events, only: [:edit, :new]

  def show
    # month = params[:month] || Time.current.month
    @events = @team.for_month(nil)
  end

  def new
    @team = Team.new
  end

  def create
    @team = Team.new(team_params)
    if @team.save
      flash[:success] = "Team #{@team.name} added successfully!"
      redirect_to action: :show, id: @team.id
    else
      flash[:error] = @team.errors.full_messages.join('<br/>')
      redirect_to action: :new
    end
  end

  def edit
  end

  def update
    @team.assign_attributes(team_params)
    if @team.save
      flash[:success] = "Team #{@team.name} updated successfully!"
    else
      flash[:error] = @team.errors.full_messages.join('<br/>')
    end
    redirect_to action: :show, id: @team.id
  end

  def index
    @teams = Team.all
  end

  def destroy
    @team.destroy

    if @team.destroyed?
      flash[:success] = "Team #{@team.name} deleted successfully!"
    else
      flash[:error] = "Failed to delete the team #{@team.name}!"
    end
    redirect_to action: :index
  end

  private

  def set_team
    @team = Team.find_by(id: params[:id])
  end

  def set_events
    @events = Event.all
  end

  def team_params
    params.require(:team)
          .permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
        when :notice then "alert alert-info"
        when :success then "alert alert-success"
        when :error then "alert alert-danger"
        when :alert then "alert alert-warning"
    end
  end

  def formatted_event_date(event_date)
    event_date.try(:strftime, '%d/%m/%Y')
  end
end

app/helpers/leaderboard_helper.rb
module LeaderboardHelper
end

app/helpers/team_events_helper.rb
module TeamEventsHelper
  def options_for_events
    events_data = @events.collect do |e|
      [e.name, e.id, disabled: @assigned_events.ids.include?(e.id)]
    end
    options_for_select(events_data, [@event.try(:name), @event.try(:id)])
  end

  def options_for_teams
    teams_data = @teams.collect do |t|
      [t.name, t.id, disabled: @assigned_teams.ids.include?(t.id)]
    end
    options_for_select(teams_data, [@team.try(:name), @team.try(:id)])
  end
end

app/views/events/_form.html.erb
<div class="card-header">
  Event Details
</div>

<div class="card-body">
  <%= render 'shared/flash_view' %>

  <div class="row mb-3">
    <div class="col-lg-3 text-left">
      <%= form.label :name %>:
    </div>
    <div class="col-lg-9 text-left">
      <%= form.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class="row mb-3">
    <div class="col-lg-3 text-left">
      <%= form.label :conducted_at %>:
    </div>
    <div class="col-lg-9 text-left">
      <%= form.text_field :conducted_at, value: formatted_event_date(@event.conducted_at), class: 'form-control', data: {"date-end-date" => "0d"} %>
    </div>
  </div>
</div>

app/views/events/edit.html.erb
<%= form_with model: @event do |form| %>
  <%= render 'form', form: form %>

  <div class="card-footer text-right form-actions">
    <%= link_to 'Cancel', events_path, class: 'btn btn-secondary pull-right mr-3' %>
    <%= form.submit 'Update', class: 'btn btn-primary pull-right' %>
  </div>
<% end %>

app/views/events/index.html.erb
<div class="card-header row">
  <div class='col-lg-7 text-left'> <h5> Events </h5> </div>
  <div class='col-lg-5 text-right'>
    <div class="btn-group" role="group">
      <%= link_to 'Add an Event', new_event_path, class: 'btn btn-secondary' %>
    </div>
  </div>
</div>

<div class="card-body">
  <table class="table table-hover font-weight-light">
    <tr>
      <th class="text-left"> Event Name </th>
      <th class="text-left"> Conducted At </th>
      <th class="text-right"> Actions </th>
    </tr>

    <% @events.each do |event| %>
      <tr>
          <td class="text-left"><%= link_to(event.name, event_path(event.id)) %> </td>
          <td class="text-left"> <%= formatted_event_date(event.conducted_at) %> </td>
          <td class="actions">
            <%= link_to edit_event_path(event), title: 'Edit Event' do %>
              <i class="material-icons button edit">edit</i>
            <% end %>

            <%= link_to event_path(event), method: :delete, data: { confirm: 'Are you sure?' }, title: 'Delete Event' do %>
              <i class="material-icons button delete">delete</i>
            <% end %>
          </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/events/new.html.erb
<%= form_with model: @event do |form| %>
  <%= render 'form', form: form %>

  <div class="card-footer text-right form-actions">
    <%= link_to 'Cancel', events_path, class: 'btn btn-secondary pull-right mr-3' %>
    <%= form.submit 'Add', class: 'btn btn-primary pull-right' %>
  </div>
<% end %>

app/views/events/show.html.erb
<div class="row card-header">
  <div class='col-lg-7 text-left'>
    <div class="row">
      <div class='col-lg-12 text-left'>
        <h5><%= @event.name %></h5>
      </div>
      <div class='col-lg-12 text-left'>
        <b> Conducted At : </b>
        <%= formatted_event_date(@event.conducted_at) %>
      </div>
    </div>
  </div>

  <div class='col-lg-5 text-right'>
    <div class="btn-group" role="group">
      <%= link_to 'Edit', edit_event_path, class: 'btn btn-secondary' %>
      <%= link_to 'Add a team', new_team_event_path(event_id: @event.id, from_event: true), class: 'btn btn-secondary' %>
    </div>
  </div>
</div>

<div class="row card-body">
  <div class='col-lg-12'>
    <%= render 'shared/flash_view' %>
    <table class="table table-hover font-weight-light">
      <tr>
        <th class="text-left"> Team </th>
        <th class="text-left"> Points </th>
        <th class="text-right"> Actions </th>
      </tr>

      <% @teams.each do |team| %>
        <tr>
            <td class="text-left"> <%= link_to team.team_name, team_path(id: team.team_id) %> </td>
            <td class="text-left"> <%= team.points %> </td>
            <td class="actions">
              <%= link_to edit_team_event_path(id: team.team_event_id, from_event: true, event_id: @event.id), title: 'Edit Details' do %>
                <i class="material-icons button edit">edit</i>
              <% end %>

              <%= link_to team_event_path(id: team.team_event_id, event_id: @event.id, from_event: true),
                          method: :delete, data: { confirm: 'Do you want to delete this event?' }, title: 'Delete Event' do %>
                <i class="material-icons button delete">delete</i>
              <% end %>
            </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CustomLeaderboard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.min.js' %>

    <%= stylesheet_link_tag "https://fonts.googleapis.com/icon?family=Material+Icons" %>
    <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker.min.css" %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <%= link_to 'Scoreboard Overview', root_path, class: 'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Actions
            </a>
              <!-- Here's the magic. Add the .animate and .slide-in classes to your .dropdown-menu and you're all set! -->
              <div class="dropdown-menu dropdown-menu-right animate slideIn" aria-labelledby="navbarDropdown">
                <%= link_to 'Scoreboard Overview', root_path, class: 'dropdown-item' %>
                <div class="dropdown-divider"></div>
                <%= link_to 'All Teams', teams_path, class: 'dropdown-item' %>
                <%= link_to 'Add New Team', new_team_path, class: 'dropdown-item' %>
                <div class="dropdown-divider"></div>
                <%= link_to 'All Events', events_path, class: 'dropdown-item' %>
                <%= link_to 'Add New Event', new_event_path, class: 'dropdown-item' %>
              </div>
            </li>
          </ul>
        </div>

      </div>
    </nav>

    <div class="container text-center mt-5">
      <div class="row">
        <div class='col-lg-3'> <br> </div>
        <div class="leaderboard col-lg-6 card mx-5 border-secondary">
          <%= yield %>
        </div>
        <div class='col-lg-3'> <br> </div>
      </div>
    </div>
  </body>
</html>

app/views/leaderboard/index.html.erb
<div id="main-leaderboard" class="row">
  <div class="col-lg-12 card px-0">
    <div class="card-header"> Team Status </div>
    <div class="card-body">
      <table class="table table-hover font-weight-light">
        <tr>
          <th> Team </th>
          <th> Total Points </th>
        </tr>

        <% @leaderboard[:team_status].each do |team| %>
        <tr>
          <td> <%= link_to(team.team_name, team_path(team.id)) %> </td>
          <td> <%= team.total_points %> </td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>

  <div class="col-lg-12 card px-0">
    <div class="card-header"> Event Details </div>
    <div class="card-body">
      <table class="table table-hover font-weight-light">
        <tr>
          <th> Event </th>
          <th> Conducted At </th>
        </tr>

        <% @leaderboard[:event_details].each do |event| %>
        <tr>
          <td> <%= link_to(event.name, event_path(event.id)) %> </td>
          <td> <%= formatted_event_date(event.conducted_at) %> </td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/shared/_flash_view.html.erb
<div class="row mb-3">
  <div class="col-lg-12">
    <% flash.each do |key, value| %>
      <div class="<%= flash_class(key.to_sym) %>">
            <%= value.html_safe %>
      </div>
    <% end %>
  </div>
</div>

app/views/team_events/_form.html.erb
<%= hidden_field_tag :from_team, @from_team %>
<%= hidden_field_tag :from_event, @from_event %>

<div class="card-header">
  Team Event Details
</div>

<div class="card-body">
  <%= render 'shared/flash_view' %>

  <div class="row mb-3">
    <div class="col-lg-3">
      <%= form.label :event %>:
    </div>
    <div class="col-lg-9">
      <%= form.select :event_id, options_for_events,
                                {
                                  selected: @event.try(:id),
                                  prompt: 'Choose Event'
                                },
                                {
                                  class: "form-control #{ @from_event || @event.present? ? 'disabled' : ''}"
                                }
      %>
    </div>
  </div>

  <div class="row mb-3">
    <div class="col-lg-3">
      <%= form.label :team %>:
    </div>
    <div class="col-lg-9">
      <%= form.select :team_id, options_for_teams,
                                { include_blank: 'Choose Team' },
                                { class: "form-control #{ @from_team || @team.present? ? 'disabled' : ''}" }
      %>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-3">
      <%= form.label :points %>:
    </div>
    <div class="col-lg-9">
      <%= form.text_field :points, class: 'form-control' %>
    </div>
  </div>
</div>

app/views/team_events/edit.html.erb
<%= form_with model: @team_event do |form| %>
  <%= render 'form', form: form %>

  <div class="card-footer text-right form-actions">
    <%= link_to 'Cancel', @from_team ? team_path(id: @team.id) : event_path(id: @event.id), class: 'btn btn-secondary pull-right mr-3' %>
    <%= form.submit 'Update', class: 'btn btn-primary pull-right' %>
  </div>
<% end %>

app/views/team_events/new.html.erb
<%= form_with model: @team_event do |form| %>
  <%= render 'form', form: form %>

  <div class="card-footer text-right form-actions">
    <%= link_to 'Cancel', @from_team ? team_path(id: @team.id) : event_path(id: @event.id), class: 'btn btn-secondary pull-right mr-3' %>
    <%= form.submit 'Add', class: 'btn btn-primary pull-right' %>
  </div>
<% end %>